# config/settings.yaml

target_urls:
  - "https://niflheim.world/"

crawl:
  rate_limit: 1
  time_out: 10
  retries: 3
  user_agent: "Mozilla/5.0 (compatible; DataCrawler/1.0)"

storage:
  output_dir: "outputs/data"
  output_format: "json"
